import postVoteRepository from './postVote.repository';
import commentVoteRepository from './commentVote.repository';
import authRepository from '../auth/auth.repository';
import { Prisma } from '../../generated/prisma/client';
import { VoteBodyDTO } from './votes.schemas';


// Returned by the set* methods when the caller's Profile row doesn't exist yet — they authenticated
// with Supabase but never ran POST /auth/profile. Lets the controller answer with a precise message
// instead of a misleading "Post/Comment not found".
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND' as const;


const votesService = {

    // ----- post votes -----

    // userId comes from req.user.id (set by requireAuth) — never trust a body-supplied user.
    // upsert handles "first vote" and "switch direction" in one atomic statement, so a fast
    // double-click can't race into a unique-constraint violation.
    async setPostVote(userId: string, postId: string, dto: VoteBodyDTO) {
        // Pre-check the caller's Profile so we can distinguish "no profile yet" from "post doesn't
        // exist" — both would otherwise surface as a P2025 inside the upsert and produce a misleading
        // "Post not found". The post's existence is still checked atomically by the upsert's connect.
        const profile = await authRepository.findProfileById(userId);
        if (!profile) {
            return PROFILE_NOT_FOUND;
        }

        // With the Profile confirmed, a P2025 below now unambiguously means the Post doesn't exist.
        try {
            return await postVoteRepository.upsert(
                // compound unique key generated by Prisma from @@unique([postId, userId])
                { postId_userId: { postId, userId } },
                // create path: connect to the existing Post and Profile rows by id
                {
                    user: { connect: { id: userId } },
                    post: { connect: { id: postId } },
                    value: dto.value,
                },
                // update path: only the vote direction can change
                { value: dto.value },
            );
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },

    // P2025 = "record to delete does not exist" — return null so the controller can map to 404
    // (i.e. "you tried to remove a vote you never cast")
    async removePostVote(userId: string, postId: string) {
        try {
            return await postVoteRepository.deleteById({ postId_userId: { postId, userId } });
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },

    // ----- comment votes -----

    // mirror of setPostVote — same upsert pattern against the (commentId, userId) compound key
    async setCommentVote(userId: string, commentId: string, dto: VoteBodyDTO) {
        // Same Profile pre-check as setPostVote, so a missing profile doesn't masquerade as
        // "Comment not found".
        const profile = await authRepository.findProfileById(userId);
        if (!profile) {
            return PROFILE_NOT_FOUND;
        }

        try {
            return await commentVoteRepository.upsert(
                { commentId_userId: { commentId, userId } },
                {
                    user: { connect: { id: userId } },
                    comment: { connect: { id: commentId } },
                    value: dto.value,
                },
                { value: dto.value },
            );
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },

    // mirror of removePostVote
    async removeCommentVote(userId: string, commentId: string) {
        try {
            return await commentVoteRepository.deleteById({ commentId_userId: { commentId, userId } });
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },
};


export default votesService;