import postVoteRepository from './postVote.repository';
import commentVoteRepository from './commentVote.repository';
import { Prisma } from '../../generated/prisma/client';
import { VoteBodyDTO } from './votes.schemas';


const votesService = {

    // ----- post votes -----

    // userId comes from req.user.id (set by requireAuth) — never trust a body-supplied user.
    // upsert handles "first vote" and "switch direction" in one atomic statement, so a fast
    // double-click can't race into a unique-constraint violation.
    // P2025 here means a connect target is missing (post id or user profile doesn't exist) —
    // return null so the controller can answer with a 404 instead of leaking a 500.
    async setPostVote(userId: string, postId: string, dto: VoteBodyDTO) {
        try {
            return await postVoteRepository.upsert(
                // compound unique key generated by Prisma from @@unique([postId, userId])
                { postId_userId: { postId, userId } },
                // create path: connect to the existing Post and Profile rows by id
                {
                    user: { connect: { id: userId } },
                    post: { connect: { id: postId } },
                    value: dto.value,
                },
                // update path: only the vote direction can change
                { value: dto.value },
            );
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },

    // P2025 = "record to delete does not exist" — return null so the controller can map to 404
    // (i.e. "you tried to remove a vote you never cast")
    async removePostVote(userId: string, postId: string) {
        try {
            return await postVoteRepository.deleteById({ postId_userId: { postId, userId } });
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },

    // ----- comment votes -----

    // mirror of setPostVote — same upsert pattern against the (commentId, userId) compound key
    async setCommentVote(userId: string, commentId: string, dto: VoteBodyDTO) {
        try {
            return await commentVoteRepository.upsert(
                { commentId_userId: { commentId, userId } },
                {
                    user: { connect: { id: userId } },
                    comment: { connect: { id: commentId } },
                    value: dto.value,
                },
                { value: dto.value },
            );
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },

    // mirror of removePostVote
    async removeCommentVote(userId: string, commentId: string) {
        try {
            return await commentVoteRepository.deleteById({ commentId_userId: { commentId, userId } });
        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') {
                return null;
            }
            throw error;
        }
    },
};


export default votesService;